@startuml
left to right direction
actor Visiteur
actor Membre
actor Bibliothecaire as Modérateur

package "Application Web (Frontend)" {
  usecase "Consulter accueil" as UC_Home
  usecase "S'authentifier" as UC_Login
  usecase "Rechercher une œuvre" as UC_Search
  usecase "Consulter une œuvre" as UC_View
  usecase "Proposer une œuvre" as UC_Upload
  usecase "Modérer une œuvre" as UC_Moderate
}

Visiteur --> UC_Home
Visiteur --> UC_Search
Visiteur --> UC_View
Visiteur --> UC_Login

Membre --> UC_Upload
Membre --> UC_Search
Membre --> UC_View

Modérateur --> UC_Moderate
Modérateur --> UC_Search

UC_Upload --> UC_Login : « include »
UC_Moderate --> UC_Login : « include »
@enduml
