@startuml
actor Utilisateur as U
boundary UI as UI
control FrontService as FS
database API as API

U -> UI : Ouvre page Login
UI -> FS : submitCredentials(email, pwd)
FS -> API : POST /auth/login {email,pwd}
API --> FS : 200 {token, role}
FS -> UI : setUser(token, role)
UI -> U : Redirection et affichage espace
@enduml
