// Styles extraits de Home.jsx pour modularisation

export const homeStyles = {
  container: {
    width: '100%',
    minHeight: '100vh',
    padding: '32px',
    boxSizing: 'border-box',
    margin: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    maxWidth: '100%',
    overflowX: 'hidden',
  },
  title: {
    fontSize: '28px',
    fontWeight: '700',
    marginTop: '48px',
    marginBottom: '18px',
    color: '#0d47a1',
  },
  sectionTitle: {
    fontSize: '18px',
    fontWeight: '600',
    marginBottom: '12px',
    color: '#333',
  },
  startedContainer: {
    display: 'flex',
    gap: '12px',
    overflowX: 'auto',
    padding: '12px',
    borderRadius: '8px',
    backgroundColor: '#f4f6fb',
    marginBottom: '28px',
  },
  startedCard: {
    minWidth: '220px',
    backgroundColor: '#fff',
    borderRadius: '8px',
    padding: '12px',
    boxShadow: '0 1px 4px rgba(0,0,0,0.08)',
    display: 'flex',
    gap: '12px',
    alignItems: 'center',
  },
  coverPlaceholder: {
    width: '56px',
    height: '80px',
    backgroundColor: '#e0e7ff',
    borderRadius: '4px',
    flexShrink: 0,
  },
  bookInfo: {
    flex: 1,
    minWidth: 0,
  },
  bookTitle: {
    fontSize: '14px',
    fontWeight: '600',
    marginBottom: '6px',
    color: '#0d47a1',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  bookAuthor: {
    fontSize: '12px',
    color: '#666',
    marginBottom: '8px',
  },
  progressBarOuter: {
    width: '100%',
    height: '8px',
    backgroundColor: '#eee',
    borderRadius: '6px',
    overflow: 'hidden',
  },
  progressBarInner: (p) => ({
    width: `${Math.max(0, Math.min(100, p))}%`,
    height: '100%',
    backgroundColor: '#4caf50',
  }),
  continueButton: {
    marginTop: '8px',
    display: 'inline-block',
    padding: '6px 10px',
    backgroundColor: '#1976d2',
    color: 'white',
    borderRadius: '6px',
    textDecoration: 'none',
    fontSize: '13px',
  },
  libraryGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))',
    gap: '16px',
  },
  libraryCard: {
    backgroundColor: '#fff',
    padding: '12px',
    borderRadius: '8px',
    boxShadow: '0 1px 6px rgba(0,0,0,0.06)',
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    minHeight: '220px',
  },
  libraryCover: {
    width: '100%',
    height: '140px',
    backgroundColor: '#e8eefb',
    borderRadius: '6px',
    objectFit: 'cover',
  },
  libraryTitle: {
    fontSize: '14px',
    fontWeight: '650',
    color: '#0d47a1',
  },
  libraryAuthor: {
    fontSize: '12px',
    color: '#666',
  },
  readButton: {
    marginTop: 'auto',
    padding: '8px 10px',
    backgroundColor: '#388e3c',
    color: 'white',
    borderRadius: '6px',
    textDecoration: 'none',
    textAlign: 'center',
    fontSize: '13px',
    flex: '1',
  },
  moderateButton: {
    marginTop: 'auto',
    padding: '8px 10px',
    backgroundColor: '#f57c00',
    color: 'white',
    borderRadius: '6px',
    textDecoration: 'none',
    textAlign: 'center',
    fontSize: '13px',
    flex: '1',
  },
  buttonContainer: {
    display: 'flex',
    gap: '8px',
    marginTop: 'auto',
  },
  backButton: {
    marginTop: '18px',
    padding: '8px 12px',
    fontSize: '14px',
    backgroundColor: '#2196f3',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
    textDecoration: 'none',
    display: 'inline-block',
  },
  preview: {
    fontSize: '11px',
    color: '#666',
    lineHeight: '1.4',
    marginTop: '8px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    display: '-webkit-box',
    WebkitLineClamp: 3,
    WebkitBoxOrient: 'vertical',
  },
  myDocumentsSection: {
    marginTop: '32px',
    marginBottom: '32px',
  },
  viewToggleContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '16px',
  },
  viewToggleButtons: {
    display: 'flex',
    gap: '8px',
    border: '1px solid #ddd',
    borderRadius: '6px',
    padding: '4px',
    backgroundColor: '#f9f9f9',
  },
  viewToggleButton: {
    padding: '8px 16px',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '500',
    transition: 'all 0.2s',
    backgroundColor: 'transparent',
    color: '#666',
  },
  viewToggleButtonActive: {
    backgroundColor: '#2196f3',
    color: 'white',
    boxShadow: '0 2px 4px rgba(33,150,243,0.3)',
  },
  libraryList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  libraryListItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    padding: '12px',
    backgroundColor: '#fff',
    borderRadius: '8px',
    boxShadow: '0 1px 4px rgba(0,0,0,0.08)',
    transition: 'box-shadow 0.2s',
    cursor: 'pointer',
  },
  libraryListItemHover: {
    boxShadow: '0 2px 8px rgba(0,0,0,0.12)',
  },
  listCover: {
    width: '80px',
    height: '112px',
    backgroundColor: '#e8eefb',
    borderRadius: '6px',
    flexShrink: 0,
    objectFit: 'cover',
  },
  listContent: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    minWidth: 0,
  },
  listTitle: {
    fontSize: '16px',
    fontWeight: '600',
    color: '#0d47a1',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  listAuthor: {
    fontSize: '14px',
    color: '#666',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  listPreview: {
    fontSize: '13px',
    color: '#888',
    lineHeight: '1.5',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
  },
  listActions: {
    display: 'flex',
    gap: '8px',
    flexShrink: 0,
  },
  listButton: {
    padding: '8px 16px',
    backgroundColor: '#388e3c',
    color: 'white',
    borderRadius: '6px',
    textDecoration: 'none',
    fontSize: '14px',
    fontWeight: '500',
    transition: 'background-color 0.2s',
  },
  listButtonModerate: {
    backgroundColor: '#f57c00',
  },
  listStatusBadge: {
    fontSize: '11px',
    padding: '4px 8px',
    borderRadius: '4px',
    fontWeight: '500',
  },
  // Pagination
  paginationContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
    marginTop: '12px',
  },
  paginationInfo: {
    fontSize: '13px',
    color: '#666',
  },
  paginationButtons: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  paginationButton: {
    padding: '6px 10px',
    fontSize: '13px',
    backgroundColor: '#2196f3',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
  },
  paginationButtonDisabled: {
    backgroundColor: '#b0bec5',
    cursor: 'not-allowed',
  }
};
